apiVersion: v1 
kind: Pod 
metadata: 
 name: envar-demo 
 labels: 
  purpose: demonstrate env-vars 
spec: 
 containers:
 - name: nginx 
   image: nginx 
   env: 
   - name: COURSE 
     value: 'KUBERNETES'
   - name: TRAINER 
     value: "SIVA"
